version: 2.1
setup: true
orbs:
    continuation: circleci/continuation@0.1.0

parameters:
    nightly:
        type: boolean
        default: false

jobs:
  build:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      # Commands will execute in macOS container
      # with Xcode 14.2.0 installed
      - run: xcodebuild -version
      - run: pip install torch
      - run: pip install torch
      - run: ls -l
      - run: python check_mac.py

workflows:
    version: 2
    setup_and_quality:
        when:
            not: <<pipeline.parameters.nightly>>
        jobs:
            - build

    nightly:
        when: <<pipeline.parameters.nightly>>
        jobs:
            - build