name: Self-hosted runner (push)

on:
  push:
    branches:
      - mac

env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  PYTEST_TIMEOUT: 60
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1
  CUDA_VISIBLE_DEVICES: 0,1

jobs:
  setup:
    name: Setup
    runs-on: macos-14
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Prepare custom environment variables
        shell: bash
        run: |          
          ls -l
          pip install torch
          python check_mac.py
          
